### ISSUE TITLE
ccl complains

### ISSUE THREAD

**Issue by vrx** [Shinmera/simple-inferiors#2]
Reader error: No external symbol named "TERMINATE-PROCESS" in package #<Package "UIOP/DRIVER"> .

**Comment by Shinmera** [comment]
What's `(asdf:asdf-version)`?

**Comment by vrx** [comment]
3.1.5

**Comment by Shinmera** [comment]
Update your ASDF.

**Comment by vrx** [comment]
sorry, what's the best way to do that ?

**Comment by Shinmera** [comment]
[Download](https://common-lisp.net/project/asdf/#downloads) ASDF and load it in your init file.

**Comment by vrx** [comment]
OK thanks :-)
